supported_os:
  - family: Ubuntu
    versions:
      - 22.04
      - 24.04
  - family: Debian
    versions:
      - 10
      - 11
  - family: Fedora
    versions:
      - 35
      - 36
server:
  - internal_ip: 192.168.0.1
  - external_ip: 8.8.8.8
